language: perl
sudo: false

install:
  - perlbrew list
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps   --missing | cpanm -n

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"

script:
  - perl util/prove
# currently included in [@Author::Plicease] bundle
#  - perl util/prove Alien::Base
  - perl util/prove FFI::Platypus
  - perl util/prove Alien::Libarchive
  - perl util/prove Acme::Alien::DontPanic
